var optimizedCodes = ['o', 'pl'];
var inProgressCodes = ['w'];
var errorCodes = ['e', 't', 'vf', '!id', '!conf', 'b', 'ed', 'cbo'];
var cachedCodes = ['c', 'clc', 'sc'];
var headersHints = ['pl'];

var codeMapping = {
  p: 'request/response proxified',
  o: 'optimized',
  '!o': 'not optimized',
  w: 'optimization in progress',
  Z: 'non optimizable page (will never be optimized, 404, 301, 302, POST, etc.).',
  ab: 'excluded because of A/B testing',
  stc: 'https status code of the origin different than 200',
  zc: 'empty content',
  ecc: 'excluded by customer configuration',
  tecc: 'tag excluded by the configuration',
  m: 'method (HEAD, PROPFIND, OPTIONS, PUT, DELETE, etc.)',
  ed: 'engine disabled',
  h: 'non HTML content (for example, JSON sent with a tex/html content type)',
  c: 'cached',
  sc: 'page is cached via SmartCache (Cache + Ajax)',
  dc: 'optimized, dynamic cache (internal engine behavior)',
  '!c': 'not cached',
  v: 'virtual object (concatenation result or outlining)',
  e: 'error, optimization failed, the page is not optimized',
  vf: 'reconstituted virtual object',
  t: 'timeout, the optimization has taken too much time, the page is not optimized',
  ccb: 'Cache CallBack, object is served from the cache by proxy (this is the case where an object doesn’t have a cookie for A/B test',
  clc: 'page is cached via Cookie Less Cache',
  cbo: 'Circuit Breaker Open, the object is not optimized because of temporary unavailability of one of the engine component',
  of: 'Overflow, show that overflow system is in place. Following flags clarify the results.',
  '!id': 'No id',
  '!conf': 'no configuration found',
  '!en': 'overflow not enabled',
  wen: 'overflow was enabled',
  en: 'overflow enabled',
  dis: 'disallow, user was send back to the waiting page',
  pp: 'partial page',
  ed: 'engine disabled',
  b: 'blocked, IP address is blocked',
  uc: 'User Canceled, request was cancelled by the user',
  pl: 'Preload headers',
  tb: 'Too big',
};

// from https://www.feitsui.com/en/blog/page/3.
var cloudfrontPOP = {
  'EZE51-C1': {
    City: 'Buenos Aires',
    Country: 'Argentina',
  },
  MEL50: {
    City: 'Melbourne',
    Country: 'Australia',
  },
  'PER50-C1': {
    City: 'Perth',
    Country: 'Australia',
  },
  'SYD1-C1': {
    City: 'Sydney',
    Country: 'Australia',
  },
  'SYD1-C2': {
    City: 'Sydney',
    Country: 'Australia',
  },
  'SYD4-C1': {
    City: 'Sydney',
    Country: 'Australia',
  },
  'SYD4-C2': {
    City: 'Sydney',
    Country: 'Australia',
  },
  'VIE50-C1': {
    City: 'Vienna',
    Country: 'Austria',
  },
  'BAH53-C1': {
    City: 'Manama',
    Country: 'Bahrain',
  },
  'BRU50-C1': {
    City: 'Brussels',
    Country: 'Belgium',
  },
  'GIG51-C1': {
    City: 'Rio de Janeiro',
    Country: 'Brazil',
  },
  'GIG51-C2': {
    City: 'Rio de Janeiro',
    Country: 'Brazil',
  },
  GRU1: {
    City: 'São Paulo',
    Country: 'Brazil',
  },
  'GRU1-C1': {
    City: 'São Paulo',
    Country: 'Brazil',
  },
  GRU50: {
    City: 'São Paulo',
    Country: 'Brazil',
  },
  'GRU50-C1': {
    City: 'São Paulo',
    Country: 'Brazil',
  },
  'YUL62-C1': {
    City: 'Montréal, QC',
    Country: 'Canada',
  },
  'YTO50-C1': {
    City: 'Toronto, ON',
    Country: 'Canada',
  },
  'SCL50-C1': {
    City: 'Santiago',
    Country: 'Chile',
  },
  BJS: {
    City: 'Beijing',
    Country: 'China',
  },
  HKG50: {
    City: 'Hong Kong',
    Country: 'China',
  },
  HKG51: {
    City: 'Hong Kong',
    Country: 'China',
  },
  HKG53: {
    City: 'Hong Kong',
    Country: 'China',
  },
  'HKG54-C1': {
    City: 'Hong Kong',
    Country: 'China',
  },
  'HKG60-C1': {
    City: 'Hong Kong',
    Country: 'China',
  },
  'HKG62-C1': {
    City: 'Hong Kong',
    Country: 'China',
  },
  SHA: {
    City: 'Shanghai',
    Country: 'China',
  },
  SZX: {
    City: 'Shenzhen',
    Country: 'China',
  },
  'TPE50-C1': {
    City: 'Taipei, TW',
    Country: 'China',
  },
  'TPE51-C1': {
    City: 'Taipei, TW',
    Country: 'China',
  },
  'TPE52-C1': {
    City: 'Taipei, TW',
    Country: 'China',
  },
  ZHY: {
    City: 'Zhongwei, Ningxia',
    Country: 'China',
  },
  'BOG50-C1': {
    City: 'Bogotá',
    Country: 'Colombia',
  },
  PRG50: {
    City: 'Prague',
    Country: 'Czech Republic',
  },
  'CPH50-C1': {
    City: 'Copenhagen',
    Country: 'Denmark',
  },
  'HEL50-C1': {
    City: 'Helsinki',
    Country: 'Finland',
  },
  MRS50: {
    City: 'Marseille',
    Country: 'France',
  },
  CDG3: {
    City: 'Paris',
    Country: 'France',
  },
  'CDG3-C1': {
    City: 'Paris',
    Country: 'France',
  },
  'CDG3-C2': {
    City: 'Paris',
    Country: 'France',
  },
  'CDG50-C1': {
    City: 'Paris',
    Country: 'France',
  },
  'CDG53-C1': {
    City: 'Paris',
    Country: 'France',
  },
  CDG54: {
    City: 'Paris',
    Country: 'France',
  },
  TXL51: {
    City: 'Berlin',
    Country: 'Germany',
  },
  'TXL52-C1': {
    City: 'Berlin',
    Country: 'Germany',
  },
  FRA2: {
    City: 'Frankfurt',
    Country: 'Germany',
  },
  'FRA2-C1': {
    City: 'Frankfurt',
    Country: 'Germany',
  },
  'FRA2-C2': {
    City: 'Frankfurt',
    Country: 'Germany',
  },
  'FRA6-C1': {
    City: 'Frankfurt',
    Country: 'Germany',
  },
  FRA50: {
    City: 'Frankfurt',
    Country: 'Germany',
  },
  'FRA50-C1': {
    City: 'Frankfurt',
    Country: 'Germany',
  },
  FRA53: {
    City: 'Frankfurt',
    Country: 'Germany',
  },
  'FRA53-C1': {
    City: 'Frankfurt',
    Country: 'Germany',
  },
  FRA54: {
    City: 'Frankfurt',
    Country: 'Germany',
  },
  FRA56: {
    City: 'Frankfurt',
    Country: 'Germany',
  },
  'MUC50-C1': {
    City: 'Munich',
    Country: 'Germany',
  },
  MUC51: {
    City: 'Munich',
    Country: 'Germany',
  },
  'MUC51-C1': {
    City: 'Munich',
    Country: 'Germany',
  },
  'BLR50-C1': {
    City: 'Bangalore',
    Country: 'India',
  },
  'BLR50-C2': {
    City: 'Bangalore',
    Country: 'India',
  },
  'BLR50-C3': {
    City: 'Bangalore',
    Country: 'India',
  },
  MAA3: {
    City: 'Chennai',
    Country: 'India',
  },
  'MAA50-C1': {
    City: 'Chennai',
    Country: 'India',
  },
  'HYD50-C1': {
    City: 'Hyderabad',
    Country: 'India',
  },
  'HYD50-C2': {
    City: 'Hyderabad',
    Country: 'India',
  },
  'HYD50-C3': {
    City: 'Hyderabad',
    Country: 'India',
  },
  'HYD50-C4': {
    City: 'Hyderabad',
    Country: 'India',
  },
  'BOM50-C1': {
    City: 'Mumbai',
    Country: 'India',
  },
  'BOM51-C1': {
    City: 'Mumbai',
    Country: 'India',
  },
  'BOM51-C2': {
    City: 'Mumbai',
    Country: 'India',
  },
  BOM52: {
    City: 'Mumbai',
    Country: 'India',
  },
  DEL51: {
    City: 'New Delhi',
    Country: 'India',
  },
  'DEL54-C1': {
    City: 'New Delhi',
    Country: 'India',
  },
  'DEL54-C3': {
    City: 'New Delhi',
    Country: 'India',
  },
  'DEL54-C4': {
    City: 'New Delhi',
    Country: 'India',
  },
  'DUB2-C1': {
    City: 'Dublin',
    Country: 'Ireland',
  },
  'TLV50-C1': {
    City: 'Tel Aviv',
    Country: 'Israel',
  },
  'MXP64-C1': {
    City: 'Milan',
    Country: 'Italy',
  },
  'MXP64-C2': {
    City: 'Milan',
    Country: 'Italy',
  },
  PMO50: {
    City: 'Palermo',
    Country: 'Italy',
  },
  'NRT12-C1': {
    City: 'Tokyo',
    Country: 'Japan',
  },
  'NRT12-C2': {
    City: 'Tokyo',
    Country: 'Japan',
  },
  'NRT12-C3': {
    City: 'Tokyo',
    Country: 'Japan',
  },
  'NRT12-C4': {
    City: 'Tokyo',
    Country: 'Japan',
  },
  NRT20: {
    City: 'Tokyo',
    Country: 'Japan',
  },
  'NRT20-C1': {
    City: 'Tokyo',
    Country: 'Japan',
  },
  'NRT20-C2': {
    City: 'Tokyo',
    Country: 'Japan',
  },
  'NRT20-C3': {
    City: 'Tokyo',
    Country: 'Japan',
  },
  'NRT20-C4': {
    City: 'Tokyo',
    Country: 'Japan',
  },
  NRT51: {
    City: 'Tokyo',
    Country: 'Japan',
  },
  'NRT51-C1': {
    City: 'Tokyo',
    Country: 'Japan',
  },
  'NRT51-C2': {
    City: 'Tokyo',
    Country: 'Japan',
  },
  'NRT51-C3': {
    City: 'Tokyo',
    Country: 'Japan',
  },
  NRT52: {
    City: 'Tokyo',
    Country: 'Japan',
  },
  NRT53: {
    City: 'Tokyo',
    Country: 'Japan',
  },
  'NRT57-C1': {
    City: 'Tokyo',
    Country: 'Japan',
  },
  'NRT57-C2': {
    City: 'Tokyo',
    Country: 'Japan',
  },
  'NRT57-C3': {
    City: 'Tokyo',
    Country: 'Japan',
  },
  'NRT57-C4': {
    City: 'Tokyo',
    Country: 'Japan',
  },
  KUL50: {
    City: 'Kuala Lumpur',
    Country: 'Malaysia',
  },
  'KUL50-C1': {
    City: 'Kuala Lumpur',
    Country: 'Malaysia',
  },
  'OSL50-C1': {
    City: 'Oslo',
    Country: 'Norway',
  },
  MNL50: {
    City: 'Manila',
    Country: 'Philippines',
  },
  'MNL50-C1': {
    City: 'Manila',
    Country: 'Philippines',
  },
  'WAW50-C1': {
    City: 'Warsaw',
    Country: 'Poland',
  },
  'LIS50-C1': {
    City: 'Lisbon',
    Country: 'Portugal',
  },
  'SIN2-C1': {
    City: 'Singapore',
    Country: 'Singapore',
  },
  'SIN5-C1': {
    City: 'Singapore',
    Country: 'Singapore',
  },
  'SIN52-C2': {
    City: 'Singapore',
    Country: 'Singapore',
  },
  CPT50: {
    City: 'Cape Town',
    Country: 'South Africa',
  },
  JNB50: {
    City: 'Johannesburg',
    Country: 'South Africa',
  },
  ICN50: {
    City: 'Seoul',
    Country: 'South Korea',
  },
  'ICN51-C1': {
    City: 'Seoul',
    Country: 'South Korea',
  },
  ICN54: {
    City: 'Seoul',
    Country: 'South Korea',
  },
  'ICN54-C1': {
    City: 'Seoul',
    Country: 'South Korea',
  },
  'ICN54-C2': {
    City: 'Seoul',
    Country: 'South Korea',
  },
  'ICN55-C1': {
    City: 'Seoul',
    Country: 'South Korea',
  },
  MAD50: {
    City: 'Madrid',
    Country: 'Spain',
  },
  'MAD50-C1': {
    City: 'Madrid',
    Country: 'Spain',
  },
  'MAD51-C1': {
    City: 'Madrid',
    Country: 'Spain',
  },
  'ARN1-C1': {
    City: 'Stockholm',
    Country: 'Sweden',
  },
  ARN53: {
    City: 'Stockholm',
    Country: 'Sweden',
  },
  ARN54: {
    City: 'Stockholm',
    Country: 'Sweden',
  },
  ZRH50: {
    City: 'Zürich',
    Country: 'Switzerland',
  },
  'ZRH50-C1': {
    City: 'Zürich',
    Country: 'Switzerland',
  },
  AMS1: {
    City: 'Amsterdam',
    Country: 'The Netherlands',
  },
  AMS50: {
    City: 'Amsterdam',
    Country: 'The Netherlands',
  },
  'AMS54-C1': {
    City: 'Amsterdam',
    Country: 'The Netherlands',
  },
  'DXB50-C1': {
    City: 'Dubai',
    Country: 'United Arab Emirates',
  },
  'FJR50-C1': {
    City: 'Fujairah',
    Country: 'United Arab Emirates',
  },
  'LHR3-C1': {
    City: 'London',
    Country: 'United Kingdom',
  },
  'LHR3-C2': {
    City: 'London',
    Country: 'United Kingdom',
  },
  LHR4: {
    City: 'London',
    Country: 'United Kingdom',
  },
  'LHR50-C1': {
    City: 'London',
    Country: 'United Kingdom',
  },
  LHR52: {
    City: 'London',
    Country: 'United Kingdom',
  },
  'LHR52-C1': {
    City: 'London',
    Country: 'United Kingdom',
  },
  'LHR61-C1': {
    City: 'London',
    Country: 'United Kingdom',
  },
  'LHR61-C2': {
    City: 'London',
    Country: 'United Kingdom',
  },
  'LHR62-C1': {
    City: 'London',
    Country: 'United Kingdom',
  },
  'LHR62-C2': {
    City: 'London',
    Country: 'United Kingdom',
  },
  'LHR62-C3': {
    City: 'London',
    Country: 'United Kingdom',
  },
  'MAN50-C1': {
    City: 'Manchester',
    Country: 'United Kingdom',
  },
  'MAN50-C2': {
    City: 'Manchester',
    Country: 'United Kingdom',
  },
  IAD16: {
    City: 'Ashburn, VA',
    Country: 'United States',
  },
  IAD53: {
    City: 'Ashburn, VA',
    Country: 'United States',
  },
  'IAD79-C1': {
    City: 'Ashburn, VA',
    Country: 'United States',
  },
  'IAD79-C2': {
    City: 'Ashburn, VA',
    Country: 'United States',
  },
  'IAD79-C3': {
    City: 'Ashburn, VA',
    Country: 'United States',
  },
  'IAD89-C1': {
    City: 'Ashburn, VA',
    Country: 'United States',
  },
  'IAD89-C2': {
    City: 'Ashburn, VA',
    Country: 'United States',
  },
  'ATL50-C1': {
    City: 'Atlanta, GA',
    Country: 'United States',
  },
  'ATL51-C1': {
    City: 'Atlanta, GA',
    Country: 'United States',
  },
  'ATL52-C1': {
    City: 'Atlanta, GA',
    Country: 'United States',
  },
  BOS50: {
    City: 'Boston, MA',
    Country: 'United States',
  },
  'BOS50-C1': {
    City: 'Boston, MA',
    Country: 'United States',
  },
  'BOS50-C2': {
    City: 'Boston, MA',
    Country: 'United States',
  },
  ORD50: {
    City: 'Chicago, IL',
    Country: 'United States',
  },
  'ORD50-C1': {
    City: 'Chicago, IL',
    Country: 'United States',
  },
  'ORD51-C1': {
    City: 'Chicago, IL',
    Country: 'United States',
  },
  'ORD51-C2': {
    City: 'Chicago, IL',
    Country: 'United States',
  },
  'ORD52-C1': {
    City: 'Chicago, IL',
    Country: 'United States',
  },
  'ORD52-C2': {
    City: 'Chicago, IL',
    Country: 'United States',
  },
  'DFW3-C1': {
    City: 'Dallas/Fort Worth, TX',
    Country: 'United States',
  },
  'DFW50-C1': {
    City: 'Dallas/Fort Worth, TX',
    Country: 'United States',
  },
  DFW53: {
    City: 'Dallas/Fort Worth, TX',
    Country: 'United States',
  },
  'DFW53-C1': {
    City: 'Dallas/Fort Worth, TX',
    Country: 'United States',
  },
  DFW54: {
    City: 'Dallas/Fort Worth, TX',
    Country: 'United States',
  },
  'DEN50-C1': {
    City: 'Denver, CO',
    Country: 'United States',
  },
  'DEN50-C2': {
    City: 'Denver, CO',
    Country: 'United States',
  },
  'HIO50-C1': {
    City: 'Hillsboro, OR',
    Country: 'United States',
  },
  'HIO51-C1': {
    City: 'Hillsboro, OR',
    Country: 'United States',
  },
  'IAH50-C1': {
    City: 'Houston, TX',
    Country: 'United States',
  },
  'IAH50-C2': {
    City: 'Houston, TX',
    Country: 'United States',
  },
  'IAH50-C3': {
    City: 'Houston, TX',
    Country: 'United States',
  },
  'IAH50-C4': {
    City: 'Houston, TX',
    Country: 'United States',
  },
  'JAX1-C1': {
    City: 'Jacksonville, FL',
    Country: 'United States',
  },
  LAX1: {
    City: 'Los Angeles, CA',
    Country: 'United States',
  },
  'LAX3-C1': {
    City: 'Los Angeles, CA',
    Country: 'United States',
  },
  'LAX3-C2': {
    City: 'Los Angeles, CA',
    Country: 'United States',
  },
  'LAX3-C3': {
    City: 'Los Angeles, CA',
    Country: 'United States',
  },
  'LAX3-C4': {
    City: 'Los Angeles, CA',
    Country: 'United States',
  },
  'MIA3-C1': {
    City: 'Miami, FL',
    Country: 'United States',
  },
  'MIA3-C2': {
    City: 'Miami, FL',
    Country: 'United States',
  },
  'MIA3-C3': {
    City: 'Miami, FL',
    Country: 'United States',
  },
  MIA50: {
    City: 'Miami, FL',
    Country: 'United States',
  },
  'MSP50-C1': {
    City: 'Minneapolis, MN',
    Country: 'United States',
  },
  JFK1: {
    City: 'New York, NY',
    Country: 'United States',
  },
  JFK5: {
    City: 'New York, NY',
    Country: 'United States',
  },
  JFK6: {
    City: 'New York, NY',
    Country: 'United States',
  },
  'JFK51-C1': {
    City: 'New York, NY',
    Country: 'United States',
  },
  EWR50: {
    City: 'Newark, NJ',
    Country: 'United States',
  },
  'EWR50-C1': {
    City: 'Newark, NJ',
    Country: 'United States',
  },
  'EWR52-C1': {
    City: 'Newark, NJ',
    Country: 'United States',
  },
  'EWR52-C2': {
    City: 'Newark, NJ',
    Country: 'United States',
  },
  'EWR52-C3': {
    City: 'Newark, NJ',
    Country: 'United States',
  },
  'EWR52-C4': {
    City: 'Newark, NJ',
    Country: 'United States',
  },
  'EWR53-C1': {
    City: 'Newark, NJ',
    Country: 'United States',
  },
  'EWR53-C2': {
    City: 'Newark, NJ',
    Country: 'United States',
  },
  PHL50: {
    City: 'Philadelphia, PA',
    Country: 'United States',
  },
  'PHL50-C1': {
    City: 'Philadelphia, PA',
    Country: 'United States',
  },
  'PHX50-C1': {
    City: 'Phoenix, AZ',
    Country: 'United States',
  },
  'PHX50-C2': {
    City: 'Phoenix, AZ',
    Country: 'United States',
  },
  'SLC50-C1': {
    City: 'Salt Lake City, UT',
    Country: 'United States',
  },
  'SFO5-C1': {
    City: 'San Francisco, CA',
    Country: 'United States',
  },
  'SFO5-C3': {
    City: 'San Francisco, CA',
    Country: 'United States',
  },
  SFO9: {
    City: 'San Francisco, CA',
    Country: 'United States',
  },
  SFO20: {
    City: 'San Francisco, CA',
    Country: 'United States',
  },
  SEA4: {
    City: 'Seattle, WA',
    Country: 'United States',
  },
  SEA19: {
    City: 'Seattle, WA',
    Country: 'United States',
  },
  'SEA19-C1': {
    City: 'Seattle, WA',
    Country: 'United States',
  },
  'SEA19-C2': {
    City: 'Seattle, WA',
    Country: 'United States',
  },
  SEA32: {
    City: 'Seattle, WA',
    Country: 'United States',
  },
  IND6: {
    City: 'South Bend, IN',
    Country: 'United States',
  },
};

var cloudflarePOP = {
  AAE: { city: 'Annabah', cca2: 'DZ' },
  ABJ: { city: 'Abidjan', cca2: 'CI' },
  ABQ: { city: 'Albuquerque', cca2: 'US' },
  ACC: { city: 'Accra', cca2: 'GH' },
  ADB: { city: 'Izmir', cca2: 'TR' },
  ADD: { city: 'Addis Ababa', cca2: 'ET' },
  ADL: { city: 'Adelaide', cca2: 'AU' },
  AGR: { city: 'Agra', cca2: 'IN' },
  AKL: { city: 'Auckland', cca2: 'NZ' },
  AKX: { city: 'Aktyubinsk', cca2: 'KZ' },
  ALA: { city: 'Almaty', cca2: 'KZ' },
  ALG: { city: 'Algiers', cca2: 'DZ' },
  AMD: { city: 'Ahmedabad', cca2: 'IN' },
  AMM: { city: 'Amman', cca2: 'JO' },
  AMS: { city: 'Amsterdam', cca2: 'NL' },
  ANC: { city: 'Anchorage', cca2: 'US' },
  ARI: { city: 'Arica', cca2: 'CL' },
  ARN: { city: 'Stockholm', cca2: 'SE' },
  ARU: { city: 'Aracatuba', cca2: 'BR' },
  ASK: { city: 'Yamoussoukro', cca2: 'CI' },
  ASU: { city: 'Asuncion', cca2: 'PY' },
  ATH: { city: 'Athens', cca2: 'GR' },
  ATL: { city: 'Atlanta', cca2: 'US' },
  AUS: { city: 'Austin', cca2: 'US' },
  BAH: { city: 'Manama', cca2: 'BH' },
  BAQ: { city: 'Barranquilla', cca2: 'CO' },
  BCN: { city: 'Barcelona', cca2: 'ES' },
  BEG: { city: 'Belgrad', cca2: 'RS' },
  BEL: { city: 'Belem', cca2: 'BR' },
  BEY: { city: 'Beirut', cca2: 'LB' },
  BGI: { city: 'Bridgetown', cca2: 'BB' },
  BGR: { city: 'Bangor', cca2: 'US' },
  BGW: { city: 'Baghdad', cca2: 'IQ' },
  BKK: { city: 'Bangkok', cca2: 'TH' },
  BLR: { city: 'Bangalore', cca2: 'IN' },
  BNA: { city: 'Nashville', cca2: 'US' },
  BNE: { city: 'Brisbane', cca2: 'AU' },
  BNU: { city: 'Blumenau', cca2: 'BR' },
  BOD: { city: 'Bordeaux/Merignac', cca2: 'FR' },
  BOG: { city: 'Bogota', cca2: 'CO' },
  BOM: { city: 'Mumbai', cca2: 'IN' },
  BOS: { city: 'Boston', cca2: 'US' },
  BRU: { city: 'Brussels', cca2: 'BE' },
  BSB: { city: 'Brasilia', cca2: 'BR' },
  BSR: { city: 'Basrah', cca2: 'IQ' },
  BTS: { city: 'Bratislava', cca2: 'SK' },
  BUD: { city: 'Budapest', cca2: 'HU' },
  BUF: { city: 'Buffalo', cca2: 'US' },
  BWN: { city: 'Bandar Seri Begawan', cca2: 'BN' },
  CAI: { city: 'Cairo', cca2: 'EG' },
  CAW: { city: 'Campos Dos Goytacazes', cca2: 'BR' },
  CBR: { city: 'Canberra', cca2: 'AU' },
  CCP: { city: 'Concepcion', cca2: 'CL' },
  CCU: { city: 'Kolkata', cca2: 'IN' },
  CDG: { city: 'Paris', cca2: 'FR' },
  CEB: { city: 'Lapu-Lapu City', cca2: 'PH' },
  CFC: { city: 'Caçador', cca2: 'BR' },
  CGB: { city: 'Cuiaba', cca2: 'BR' },
  CGK: { city: 'Jakarta', cca2: 'ID' },
  CGP: { city: 'Chittagong', cca2: 'BD' },
  CGY: { city: 'Cagayan De Oro City', cca2: 'PH' },
  CHC: { city: 'Christchurch', cca2: 'NZ' },
  CJB: { city: 'Coimbatore', cca2: 'IN' },
  CLE: { city: 'Cleveland', cca2: 'US' },
  CLO: { city: 'Cali', cca2: 'CO' },
  CLT: { city: 'Charlotte', cca2: 'US' },
  CMB: { city: 'Colombo', cca2: 'LK' },
  CMH: { city: 'Columbus', cca2: 'US' },
  CNF: { city: 'Belo Horizonte', cca2: 'BR' },
  CNN: { city: 'Mattanur', cca2: 'IN' },
  CNX: { city: 'Chiang Mai', cca2: 'TH' },
  COK: { city: 'Cochin', cca2: 'IN' },
  COR: { city: 'Cordoba', cca2: 'AR' },
  CPH: { city: 'Copenhagen', cca2: 'DK' },
  CPT: { city: 'Cape Town', cca2: 'ZA' },
  CRK: { city: 'Angeles City', cca2: 'PH' },
  CWB: { city: 'Curitiba', cca2: 'BR' },
  CZL: { city: 'Constantine', cca2: 'DZ' },
  DAC: { city: 'Dhaka', cca2: 'BD' },
  DAD: { city: 'Da Nang', cca2: 'VN' },
  DAR: { city: 'Dar es Salaam', cca2: 'TZ' },
  DEL: { city: 'New Delhi', cca2: 'IN' },
  DEN: { city: 'Denver', cca2: 'US' },
  DFW: { city: 'Dallas-Fort Worth', cca2: 'US' },
  DKR: { city: 'Dakar', cca2: 'SN' },
  DME: { city: 'Moscow', cca2: 'RU' },
  DMM: { city: 'Ad Dammam', cca2: 'SA' },
  DOH: { city: 'Doha', cca2: 'QA' },
  DPS: { city: 'Denpasar-Bali Island', cca2: 'ID' },
  DTW: { city: 'Detroit', cca2: 'US' },
  DUB: { city: 'Dublin', cca2: 'IE' },
  DUR: { city: 'Durban', cca2: 'ZA' },
  DUS: { city: 'Dusseldorf', cca2: 'DE' },
  DXB: { city: 'Dubai', cca2: 'AE' },
  EBB: { city: 'Kampala', cca2: 'UG' },
  EBL: { city: 'Arbil', cca2: 'IQ' },
  EVN: { city: 'Yerevan', cca2: 'AM' },
  EWR: { city: 'Newark', cca2: 'US' },
  EZE: { city: 'Ezeiza', cca2: 'AR' },
  FCO: { city: 'Rome', cca2: 'IT' },
  FIH: { city: 'Kinshasa', cca2: 'CD' },
  FLN: { city: 'Florianopolis', cca2: 'BR' },
  FOR: { city: 'Fortaleza', cca2: 'BR' },
  FRA: { city: 'Frankfurt-am-Main', cca2: 'DE' },
  FRU: { city: 'Bishkek', cca2: 'KG' },
  FSD: { city: 'Sioux Falls', cca2: 'US' },
  FUK: { city: 'Fukuoka', cca2: 'JP' },
  GBE: { city: 'Gaborone', cca2: 'BW' },
  GDL: { city: 'Guadalajara', cca2: 'MX' },
  GEO: { city: 'Georgetown', cca2: 'GY' },
  GIG: { city: 'Rio De Janeiro', cca2: 'BR' },
  GND: { city: "Saint George's", cca2: 'GD' },
  GOT: { city: 'Gothenburg', cca2: 'SE' },
  GRU: { city: 'Sao Paulo', cca2: 'BR' },
  GUA: { city: 'Guatemala City', cca2: 'GT' },
  GUM: { city: 'Hagatna', cca2: 'GU' },
  GVA: { city: 'Geneva', cca2: 'CH' },
  GYD: { city: 'Baku', cca2: 'AZ' },
  GYE: { city: 'Guayaquil', cca2: 'EC' },
  GYN: { city: 'Goiania', cca2: 'BR' },
  HAM: { city: 'Hamburg', cca2: 'DE' },
  HAN: { city: 'Hanoi', cca2: 'VN' },
  HBA: { city: 'Hobart', cca2: 'AU' },
  HEL: { city: 'Helsinki', cca2: 'FI' },
  HFA: { city: 'Haifa', cca2: 'IL' },
  HKG: { city: 'Hong Kong', cca2: 'HK' },
  HNL: { city: 'Honolulu', cca2: 'US' },
  HRE: { city: 'Harare', cca2: 'ZW' },
  HYD: { city: 'Hyderabad', cca2: 'IN' },
  IAD: { city: 'Dulles', cca2: 'US' },
  IAH: { city: 'Houston', cca2: 'US' },
  ICN: { city: 'Seoul', cca2: 'KR' },
  IND: { city: 'Indianapolis', cca2: 'US' },
  ISB: { city: 'Islamabad', cca2: 'PK' },
  IST: { city: 'Arnavutkoy', cca2: 'TR' },
  ISU: { city: 'Sulaymaniyah', cca2: 'IQ' },
  IXC: { city: 'Chandigarh', cca2: 'IN' },
  JAX: { city: 'Jacksonville', cca2: 'US' },
  JDO: { city: 'Juazeiro Do Norte', cca2: 'BR' },
  JED: { city: 'Jeddah', cca2: 'SA' },
  JHB: { city: 'Senai', cca2: 'MY' },
  JIB: { city: 'Djibouti City', cca2: 'DJ' },
  JNB: { city: 'Johannesburg', cca2: 'ZA' },
  JOG: { city: 'Yogyakarta-Java Island', cca2: 'ID' },
  JOI: { city: 'Joinville', cca2: 'BR' },
  KBP: { city: 'Kiev', cca2: 'UA' },
  KCH: { city: 'Kuching', cca2: 'MY' },
  KEF: { city: 'Reykjavik', cca2: 'IS' },
  KGL: { city: 'Kigali', cca2: 'RW' },
  KHH: { city: 'Kaohsiung City', cca2: 'TW' },
  KHI: { city: 'Karachi', cca2: 'PK' },
  KIN: { city: 'Kingston', cca2: 'JM' },
  KIX: { city: 'Osaka', cca2: 'JP' },
  KJA: { city: 'Krasnoyarsk', cca2: 'RU' },
  KNU: { city: 'Kanpur', cca2: 'IN' },
  KTM: { city: 'Kathmandu', cca2: 'NP' },
  KUL: { city: 'Kuala Lumpur', cca2: 'MY' },
  KWI: { city: 'Kuwait City', cca2: 'KW' },
  LAD: { city: 'Luanda', cca2: 'AO' },
  LAS: { city: 'Las Vegas', cca2: 'US' },
  LAX: { city: 'Los Angeles', cca2: 'US' },
  LCA: { city: 'Larnarca', cca2: 'CY' },
  LED: { city: 'St. Petersburg', cca2: 'RU' },
  LHE: { city: 'Lahore', cca2: 'PK' },
  LHR: { city: 'London', cca2: 'GB' },
  LIM: { city: 'Lima', cca2: 'PE' },
  LIS: { city: 'Lisbon', cca2: 'PT' },
  LLK: { city: 'Lankaran', cca2: 'AZ' },
  LLW: { city: 'Lilongwe', cca2: 'MW' },
  LOS: { city: 'Lagos', cca2: 'NG' },
  LPB: { city: 'La Paz / El Alto', cca2: 'BO' },
  LUN: { city: 'Lusaka', cca2: 'ZM' },
  LUX: { city: 'Luxembourg', cca2: 'LU' },
  LYS: { city: 'Lyon', cca2: 'FR' },
  MAA: { city: 'Chennai', cca2: 'IN' },
  MAD: { city: 'Madrid', cca2: 'ES' },
  MAN: { city: 'Manchester', cca2: 'GB' },
  MAO: { city: 'Manaus', cca2: 'BR' },
  MBA: { city: 'Mombasa', cca2: 'KE' },
  MCI: { city: 'Kansas City', cca2: 'US' },
  MCT: { city: 'Muscat', cca2: 'OM' },
  MDE: { city: 'Rionegro', cca2: 'CO' },
  MEL: { city: 'Melbourne', cca2: 'AU' },
  MEM: { city: 'Memphis', cca2: 'US' },
  MEX: { city: 'Mexico City', cca2: 'MX' },
  MFM: { city: 'Taipa', cca2: 'MO' },
  MIA: { city: 'Miami', cca2: 'US' },
  MLA: { city: 'Luqa', cca2: 'MT' },
  MLE: { city: 'Male', cca2: 'MV' },
  MLG: { city: 'Malang-Java Island', cca2: 'ID' },
  MNL: { city: 'Manila', cca2: 'PH' },
  MPM: { city: 'Maputo', cca2: 'MZ' },
  MRS: { city: 'Marseille', cca2: 'FR' },
  MRU: { city: 'Port Louis', cca2: 'MU' },
  MSP: { city: 'Minneapolis', cca2: 'US' },
  MSQ: { city: 'Minsk', cca2: 'BY' },
  MUC: { city: 'Munich', cca2: 'DE' },
  MXP: { city: 'Milan', cca2: 'IT' },
  NAG: { city: 'Naqpur', cca2: 'IN' },
  NBO: { city: 'Nairobi', cca2: 'KE' },
  NJF: { city: 'Najaf', cca2: 'IQ' },
  NOU: { city: 'Noumea', cca2: 'NC' },
  NQN: { city: 'Neuquen', cca2: 'AR' },
  NQZ: { city: 'Astana', cca2: 'KZ' },
  NRT: { city: 'Tokyo', cca2: 'JP' },
  NVT: { city: 'Navegantes', cca2: 'BR' },
  OKA: { city: 'Naha', cca2: 'JP' },
  OKC: { city: 'Oklahoma City', cca2: 'US' },
  OMA: { city: 'Omaha', cca2: 'US' },
  ORD: { city: 'Chicago', cca2: 'US' },
  ORF: { city: 'Norfolk', cca2: 'US' },
  ORN: { city: 'Oran', cca2: 'DZ' },
  OSL: { city: 'Oslo', cca2: 'NO' },
  OTP: { city: 'Bucharest', cca2: 'RO' },
  OUA: { city: 'Ouagadougou', cca2: 'BF' },
  PAT: { city: 'Patna', cca2: 'IN' },
  PBH: { city: 'Paro', cca2: 'BT' },
  PBM: { city: 'Zandery', cca2: 'SR' },
  PDX: { city: 'Portland', cca2: 'US' },
  PER: { city: 'Perth', cca2: 'AU' },
  PHL: { city: 'Philadelphia', cca2: 'US' },
  PHX: { city: 'Phoenix', cca2: 'US' },
  PIT: { city: 'Pittsburgh', cca2: 'US' },
  PMO: { city: 'Palermo', cca2: 'IT' },
  PMW: { city: 'Palmas', cca2: 'BR' },
  PNH: { city: 'Phnom Penh', cca2: 'KH' },
  POA: { city: 'Porto Alegre', cca2: 'BR' },
  POS: { city: 'Port of Spain', cca2: 'TT' },
  PPT: { city: 'Papeete', cca2: 'PF' },
  PRG: { city: 'Prague', cca2: 'CZ' },
  PTY: { city: 'Tocumen', cca2: 'PA' },
  QRO: { city: 'Queretaro', cca2: 'MX' },
  QWJ: { city: 'Americana', cca2: 'BR' },
  RAO: { city: 'Ribeirao Preto', cca2: 'BR' },
  RDU: { city: 'Raleigh/Durham', cca2: 'US' },
  REC: { city: 'Recife', cca2: 'BR' },
  RIC: { city: 'Richmond', cca2: 'US' },
  RIX: { city: 'Riga', cca2: 'LV' },
  RUH: { city: 'Riyadh', cca2: 'SA' },
  RUN: { city: 'St Denis', cca2: 'RE' },
  SAN: { city: 'San Diego', cca2: 'US' },
  SAP: { city: 'La Mesa', cca2: 'HN' },
  SAT: { city: 'San Antonio', cca2: 'US' },
  SCL: { city: 'Santiago', cca2: 'CL' },
  SDQ: { city: 'Santo Domingo', cca2: 'DO' },
  SEA: { city: 'Seattle', cca2: 'US' },
  SFO: { city: 'San Francisco', cca2: 'US' },
  SGN: { city: 'Ho Chi Minh City', cca2: 'VN' },
  SIN: { city: 'Singapore', cca2: 'SG' },
  SJC: { city: 'San Jose', cca2: 'US' },
  SJK: { city: 'Sao Jose Dos Campos', cca2: 'BR' },
  SJO: { city: 'San Jose', cca2: 'CR' },
  SJP: { city: 'Sao Jose Do Rio Preto', cca2: 'BR' },
  SJU: { city: 'San Juan', cca2: 'PR' },
  SKG: { city: 'Thessaloniki', cca2: 'GR' },
  SKP: { city: 'Skopje', cca2: 'MK' },
  SLC: { city: 'Salt Lake City', cca2: 'US' },
  SMF: { city: 'Sacramento', cca2: 'US' },
  SOD: { city: 'Sorocaba', cca2: 'BR' },
  SOF: { city: 'Sofia', cca2: 'BG' },
  SSA: { city: 'Salvador', cca2: 'BR' },
  STI: { city: 'Santiago', cca2: 'DO' },
  STL: { city: 'St Louis', cca2: 'US' },
  STR: { city: 'Stuttgart', cca2: 'DE' },
  SUV: { city: 'Nausori', cca2: 'FJ' },
  SYD: { city: 'Sydney', cca2: 'AU' },
  TBS: { city: 'Tbilisi', cca2: 'GE' },
  TGU: { city: 'Tegucigalpa', cca2: 'HN' },
  TIA: { city: 'Tirana', cca2: 'AL' },
  TLH: { city: 'Tallahassee', cca2: 'US' },
  TLL: { city: 'Tallinn', cca2: 'EE' },
  TLV: { city: 'Tel Aviv', cca2: 'IL' },
  TNR: { city: 'Antananarivo', cca2: 'MG' },
  TPA: { city: 'Tampa', cca2: 'US' },
  TPE: { city: 'Taipei', cca2: 'TW' },
  TUN: { city: 'Tunis', cca2: 'TN' },
  TXL: { city: 'Berlin', cca2: 'DE' },
  UDI: { city: 'Uberlandia', cca2: 'BR' },
  UIO: { city: 'Quito', cca2: 'EC' },
  ULN: { city: 'Ulan Bator', cca2: 'MN' },
  URT: { city: 'Surat Thani', cca2: 'TH' },
  VCP: { city: 'Campinas', cca2: 'BR' },
  VIE: { city: 'Vienna', cca2: 'AT' },
  VIX: { city: 'Vitoria', cca2: 'BR' },
  VNO: { city: 'Vilnius', cca2: 'LT' },
  VTE: { city: 'Vientiane', cca2: 'LA' },
  WAW: { city: 'Warsaw', cca2: 'PL' },
  WDH: { city: 'Windhoek', cca2: 'NA' },
  WRO: { city: 'Wroclaw', cca2: 'PL' },
  XAP: { city: 'Chapeco', cca2: 'BR' },
  XNH: { city: 'Nasiriyah', cca2: 'IQ' },
  YHZ: { city: 'Halifax', cca2: 'CA' },
  YOW: { city: 'Ottawa', cca2: 'CA' },
  YUL: { city: 'Montreal', cca2: 'CA' },
  YVR: { city: 'Vancouver', cca2: 'CA' },
  YWG: { city: 'Winnipeg', cca2: 'CA' },
  YXE: { city: 'Saskatoon', cca2: 'CA' },
  YYC: { city: 'Calgary', cca2: 'CA' },
  YYZ: { city: 'Toronto', cca2: 'CA' },
  ZAG: { city: 'Zagreb', cca2: 'HR' },
  ZDM: { city: 'Ramallah', cca2: 'PS' },
  ZRH: { city: 'Zurich', cca2: 'CH' },
};
var frzPoP = [
  {
    pop: 'frpa',
    popName: 'Paris (France)',
    ip: ['195.154.68.81', '195.154.68.55', '51.159.84.68'],
  },
  {
    pop: 'frstag',
    popName: 'Paris (Staging environment)',
    ip: ['195.154.71.199'],
  },
];

var frzIP = frzPoP.reduce(function (acc, arr) {
  return { ip: acc.ip.concat(arr.ip) };
}).ip;
